package httpapi

import (
	"log/slog"
	"net/http"
	"strings"

	"local-agent-workbench/internal/app"
	"local-agent-workbench/internal/events"
)

type Server struct {
	app           *app.App
	eventHub      *events.Hub
	logger        *slog.Logger
	allowedOrigin string
	apiToken      string
	mux           *http.ServeMux
}

func New(application *app.App, eventHub *events.Hub, logger *slog.Logger, allowedOrigin, apiToken string) *Server {
	if logger == nil {
		logger = slog.Default()
	}
	if eventHub == nil {
		eventHub = events.NewHub()
	}
	s := &Server{app: application, eventHub: eventHub, logger: logger, allowedOrigin: allowedOrigin, apiToken: strings.TrimSpace(apiToken), mux: http.NewServeMux()}
	s.routes()
	return s
}

func (s *Server) Handler() http.Handler { return s.middleware(s.mux) }

func (s *Server) routes() {
	// Инструменты Point для исполнителей, принимающих их только по MCP.
	// Права здесь не решаются: сервер спрашивает исполнителя сущности,
	// открывшей сессию, — тот же, что отвечает на обычном пути.
	s.mux.HandleFunc("POST /mcp", s.app.MCPHandler())
	// Клиент MCP пробует открыть поток событий отдельным GET. Потока здесь нет:
	// вызовы идут запрос-ответом. Молчаливый 405 маршрутизатора это не
	// объясняет, поэтому отвечаем словами протокола.
	s.mux.HandleFunc("GET /mcp", s.app.MCPStreamRefusal())
	s.mux.HandleFunc("GET /api/health", func(w http.ResponseWriter, _ *http.Request) {
		s.write(w, http.StatusOK, map[string]any{"status": "ok", "version": app.Version})
	})
	s.mux.HandleFunc("GET /api/system/diagnostics", s.systemDiagnostics)
	s.mux.HandleFunc("GET /api/system/backups", s.listSystemBackups)
	s.mux.HandleFunc("POST /api/system/backups", s.createSystemBackup)
	s.mux.HandleFunc("GET /api/bootstrap", s.bootstrap)
	s.mux.HandleFunc("GET /api/state/runtime", s.runtimeState)
	s.mux.HandleFunc("GET /api/state/guild", s.guildState)
	s.mux.HandleFunc("POST /api/workspaces/open", s.openWorkspace)
	s.mux.HandleFunc("POST /api/intakes", s.createIntake)
	s.mux.HandleFunc("GET /api/intakes", s.listIntakes)
	s.mux.HandleFunc("GET /api/intakes/{id}", s.getIntake)
	s.mux.HandleFunc("POST /api/intakes/{id}/approve", s.approveIntake)
	s.mux.HandleFunc("GET /api/intakes/{id}/evidence", s.intakeEvidence)
	s.mux.HandleFunc("POST /api/intakes/{id}/expand", s.expandIntake)
	s.mux.HandleFunc("GET /api/workspaces/tree", s.workspaceTree)
	s.mux.HandleFunc("GET /api/workspace/model-routing", s.getWorkspaceModelRouting)
	s.mux.HandleFunc("PUT /api/workspace/model-routing", s.saveWorkspaceModelRouting)
	s.mux.HandleFunc("GET /api/files", s.readFile)
	s.mux.HandleFunc("PUT /api/files", s.saveFile)
	s.mux.HandleFunc("GET /api/search", s.search)
	s.mux.HandleFunc("POST /api/terminal", s.runTerminalCommand)
	s.mux.HandleFunc("POST /api/profiles", s.saveProfile)
	s.mux.HandleFunc("DELETE /api/profiles/{id}", s.deleteProfile)
	s.mux.HandleFunc("POST /api/custom-tools", s.saveCustomTool)
	s.mux.HandleFunc("POST /api/custom-tools/preview", s.previewCustomTool)
	s.mux.HandleFunc("POST /api/tools/preview", s.previewTool)
	s.mux.HandleFunc("POST /api/tools/execution-approvals", s.requestToolExecutionApproval)
	s.mux.HandleFunc("POST /api/tools/execution-approvals/{id}/resolve", s.resolveToolExecutionApproval)
	s.mux.HandleFunc("POST /api/tools/execute", s.executeTool)
	s.mux.HandleFunc("DELETE /api/custom-tools/{id}", s.deleteCustomTool)
	s.mux.HandleFunc("POST /api/providers/probe", s.probeProvider)
	s.mux.HandleFunc("POST /api/providers/capability-probe", s.probeModelCapability)
	s.mux.HandleFunc("GET /api/index/status", s.projectIndexStatus)
	s.mux.HandleFunc("GET /api/index/search", s.searchIndex)
	s.mux.HandleFunc("POST /api/index/update", s.updateProjectIndex)
	s.mux.HandleFunc("POST /api/index/invalidate", s.invalidateProjectIndex)
	s.mux.HandleFunc("POST /api/index/rebuild", s.rebuildProjectIndex)
	s.mux.HandleFunc("POST /api/context/preview", s.previewContext)
	s.mux.HandleFunc("POST /api/workflows", s.saveWorkflow)
	s.mux.HandleFunc("POST /api/workflows/validate", s.validateWorkflow)
	s.mux.HandleFunc("DELETE /api/workflows/{id}", s.deleteWorkflow)
	s.mux.HandleFunc("GET /api/workflow-runs", s.workflowRuns)
	s.mux.HandleFunc("POST /api/workflow-runs", s.startWorkflow)
	s.mux.HandleFunc("GET /api/workflow-runs/{id}", s.workflowRunDetails)
	s.mux.HandleFunc("POST /api/workflow-runs/{id}/cancel", s.cancelWorkflowRun)
	s.mux.HandleFunc("POST /api/workflow-runs/{id}/steps/{stepId}/claim", s.claimWorkflowStep)
	s.mux.HandleFunc("POST /api/workflow-runs/{id}/steps/{stepId}/heartbeat", s.heartbeatWorkflowStep)
	s.mux.HandleFunc("POST /api/workflow-runs/{id}/steps/{stepId}/complete", s.completeWorkflowStep)
	s.mux.HandleFunc("GET /api/decisions", s.decisions)
	s.mux.HandleFunc("POST /api/egress-asks/{id}/resolve", s.resolveEgressAsk)
	s.mux.HandleFunc("POST /api/master/sessions", s.masterSessionUpdate)
	s.mux.HandleFunc("GET /api/master/history", s.masterHistory)
	s.mux.HandleFunc("GET /api/master/skills", s.masterDevelopment)
	s.mux.HandleFunc("GET /api/master/learning", s.masterDevelopment)
	s.mux.HandleFunc("POST /api/master/learning", s.masterLearningUpdate)
	s.mux.HandleFunc("POST /api/master/skills/{id}/rollback", s.masterSkillRollback)
	// Каталог чатов Чертога — единственный маршрут мастера, который смотрит за
	// пределы текущего мира. Только GET и только метаданные; см. комментарий у
	// App.MasterChatDirectory о границах этого послабления.
	s.mux.HandleFunc("GET /api/master/directory", s.masterDirectory)
	s.mux.HandleFunc("POST /api/master/turns", s.masterStartTurn)
	// Agent Hub v2 contracts. The Master owns creation/revision; approval is a
	// single idempotent transaction bound to the exact reviewed digest.
	s.mux.HandleFunc("POST /api/v2/master/turns", s.masterStartTurnV2)
	s.mux.HandleFunc("GET /api/v2/master/turns/{id}", s.masterGetTurn)
	s.mux.HandleFunc("GET /api/v2/master/turns/{id}/events", s.masterEvents)
	s.mux.HandleFunc("POST /api/v2/master/turns/{id}/cancel", s.masterCancelTurn)
	s.mux.HandleFunc("POST /api/v2/sources/preview", s.previewSourceV2)
	s.mux.HandleFunc("GET /api/v2/sources/{id}", s.getSourceSnapshotV2)
	s.mux.HandleFunc("POST /api/v2/sources/{id}/refresh", s.refreshSourceSnapshotV2)
	s.mux.HandleFunc("GET /api/v2/model-certifications", s.modelCertificationsV2)
	s.mux.HandleFunc("GET /api/v2/connections/{id}/capabilities", s.connectionCapabilitiesV2)
	s.mux.HandleFunc("POST /api/v2/work-orders", s.createWorkOrderV2)
	s.mux.HandleFunc("GET /api/v2/work-orders/{id}", s.getWorkOrderV2)
	s.mux.HandleFunc("DELETE /api/v2/work-orders/{id}", s.deleteWorkOrderV2)
	s.mux.HandleFunc("GET /api/v2/work-orders/{id}/diffs", s.listWorkOrderDiffsV2)
	s.mux.HandleFunc("POST /api/v2/work-orders/{id}/revise", s.reviseWorkOrderV2)
	s.mux.HandleFunc("POST /api/v2/work-orders/{id}/approve", s.approveWorkOrderV2)
	s.mux.HandleFunc("POST /api/v2/master/quests/{id}/{action}", s.controlWorkOrderQuestV2)
	s.mux.HandleFunc("GET /api/v2/master/quests/{id}", s.getWorkOrderQuestV2)
	s.mux.HandleFunc("GET /api/v2/master/quests/{id}/evidence", s.questEvidenceBundle)
	s.mux.HandleFunc("POST /api/v2/master/quests/{id}/application/{action}", s.controlDeliveredApplicationV2)
	s.mux.HandleFunc("GET /api/master/turns/{id}", s.masterGetTurn)
	s.mux.HandleFunc("GET /api/master/turns/{id}/events", s.masterEvents)
	s.mux.HandleFunc("POST /api/master/turns/{id}/cancel", s.masterCancelTurn)
	s.mux.HandleFunc("POST /api/master/conversations/{id}/fork", s.masterFork)
	s.mux.HandleFunc("GET /api/master/conversations/{id}/export", s.masterExport)
	s.mux.HandleFunc("GET /api/master/conversations/{id}/messages", s.masterPage)
	s.mux.HandleFunc("POST /api/master/chat", s.masterChat)
	s.mux.HandleFunc("POST /api/reports", s.generateReport)
	s.mux.HandleFunc("POST /api/master/messages/{id}/feedback", s.masterMessageFeedback)
	s.mux.HandleFunc("GET /api/files/history", s.fileHistory)
	s.mux.HandleFunc("GET /api/runs", s.runs)
	s.mux.HandleFunc("POST /api/runs/preview", s.previewRun)
	s.mux.HandleFunc("POST /api/runs/fast-agent", s.startFastAgent)
	s.mux.HandleFunc("POST /api/runs", s.startRun)
	s.mux.HandleFunc("GET /api/runs/{id}", s.runDetails)
	s.mux.HandleFunc("POST /api/runs/{id}/cancel", s.cancelRun)
	s.mux.HandleFunc("POST /api/runs/{id}/pause", s.pauseRun)
	s.mux.HandleFunc("POST /api/runs/{id}/resume", s.resumeRun)
	s.mux.HandleFunc("POST /api/runs/{id}/undo", s.undoRunPatches)
	s.mux.HandleFunc("POST /api/runs/{id}/extend-active-time", s.extendActiveTime)
	s.mux.HandleFunc("POST /api/runs/{id}/message", s.injectRunMessage)
	s.mux.HandleFunc("POST /api/runs/{id}/forbid-file", s.forbidRunFile)
	s.mux.HandleFunc("POST /api/runs/{id}/context-amend", s.amendRunContext)
	s.mux.HandleFunc("POST /api/runs/{id}/context-add", s.addRunContext)
	s.mux.HandleFunc("GET /api/runs/{id}/context-inspector", s.runContextInspector)
	s.mux.HandleFunc("POST /api/approvals/{id}/resolve", s.resolveApproval)
	s.mux.HandleFunc("POST /api/patches/{id}/revert", s.revertPatch)
	s.mux.HandleFunc("GET /api/companion/live", s.companionLive)
	s.mux.HandleFunc("POST /api/companion/chat", s.companionChat)
	s.mux.HandleFunc("POST /api/companion/propose", s.companionPropose)
	s.mux.HandleFunc("GET /api/companion/history", s.companionHistory)
	s.mux.HandleFunc("DELETE /api/companion/history", s.clearCompanionHistory)
	s.mux.HandleFunc("POST /api/companion/interventions/{id}/dismiss", s.dismissCompanionIntervention)
	s.mux.HandleFunc("DELETE /api/companion/interventions/dismissed", s.restoreCompanionInterventions)
	s.mux.HandleFunc("POST /api/companion/actions/decide", s.decideCompanionAction)
	s.mux.HandleFunc("POST /api/ide/observations", s.recordIDEObservations)
	s.mux.HandleFunc("GET /api/model-candidates", s.modelCandidates)
	s.mux.HandleFunc("GET /api/model-capability-evidence", s.modelCapabilityEvidence)
	s.mux.HandleFunc("GET /api/agent-prep-chains", s.agentPrepChains)
	s.mux.HandleFunc("GET /api/flow-runs/{id}/team-events", s.teamEvents)
	s.mux.HandleFunc("POST /api/quests/{id}/reconcile-controller", s.reconcileProjectController)
	s.mux.HandleFunc("POST /api/executions/{id}/resume-runtime", s.resumeExternalExecution)
	s.mux.HandleFunc("POST /api/executions/{id}/stop-runtime", s.stopExternalExecution)
	s.mux.HandleFunc("POST /api/quest-proposals/decide", s.decideQuestProposal)
	s.mux.HandleFunc("GET /api/quest-proposals/{id}/brief-history", func(w http.ResponseWriter, r *http.Request) {
		value, err := s.app.TaskBriefHistory(r.Context(), r.PathValue("id"))
		s.result(w, value, err)
	})
	s.mux.HandleFunc("POST /api/companion/config", s.saveCompanionConfig)
	s.mux.HandleFunc("POST /api/orchestrator/config", s.saveOrchestratorConfig)
	s.mux.HandleFunc("POST /api/orchestrator/policy", s.orchestratorPolicy)
	s.mux.HandleFunc("POST /api/change-sets/{id}/apply", s.applyChangeSet)
	s.mux.HandleFunc("POST /api/change-sets/{id}/reject", s.rejectChangeSet)
	s.mux.HandleFunc("POST /api/change-sets/{id}/revert", s.revertChangeSet)
	s.mux.HandleFunc("POST /api/change-sets/{id}/resolve", s.resolveChangeSet)
	s.mux.HandleFunc("POST /api/connections", s.saveConnection)
	s.mux.HandleFunc("POST /api/blueprints", s.saveBlueprint)
	s.mux.HandleFunc("POST /api/project-agents/preview-prompt", s.previewCompiledPrompt)
	s.mux.HandleFunc("POST /api/project-agents/capability", s.agentCapability)
	s.mux.HandleFunc("POST /api/project-agents/capability-delta", s.agentCapabilityDelta)
	s.mux.HandleFunc("POST /api/project-agents", s.saveProjectAgent)
	s.mux.HandleFunc("DELETE /api/project-agents/{id}", s.deleteProjectAgent)
	s.mux.HandleFunc("POST /api/project-agents/{id}/activate-draft", s.activateProjectAgentDraft)
	s.mux.HandleFunc("POST /api/project-agents/{id}/reject-draft", s.rejectProjectAgentDraft)
	s.mux.HandleFunc("DELETE /api/blueprints/{id}", s.deleteBlueprint)
	s.mux.HandleFunc("POST /api/project-agents/{id}/apply-blueprint", s.applyBlueprintToAgent)
	s.mux.HandleFunc("POST /api/project-agents/{id}/update-blueprint", s.updateBlueprintFromAgent)
	s.mux.HandleFunc("GET /api/project-agents/{id}/diff", s.diffProjectAgent)
	s.mux.HandleFunc("POST /api/skills", s.saveSkill)
	s.mux.HandleFunc("POST /api/project-skills/equip", s.equipSkill)
	s.mux.HandleFunc("POST /api/project-skills/preview", s.previewSkillEquip)
	s.mux.HandleFunc("POST /api/teams", s.saveTeam)
	s.mux.HandleFunc("DELETE /api/teams/{id}", s.deleteTeam)
	s.mux.HandleFunc("POST /api/quests", s.saveQuest)
	s.mux.HandleFunc("DELETE /api/quests/{id}", s.deleteQuest)
	s.mux.HandleFunc("POST /api/quests/{id}/purge", s.purgeQuest)
	s.mux.HandleFunc("POST /api/flows", s.saveFlow)
	s.mux.HandleFunc("GET /api/flows/{id}", s.getFlow)
	s.mux.HandleFunc("DELETE /api/flows/{id}", s.deleteFlow)
	s.mux.HandleFunc("POST /api/flows/compile-workflow", s.compileWorkflow)
	s.mux.HandleFunc("POST /api/flow-runs", s.startFlowRun)
	s.mux.HandleFunc("GET /api/flow-runs/{id}/handoffs", s.flowHandoffs)
	s.mux.HandleFunc("POST /api/flow-runs/{id}/tick", s.tickFlowRun)
	s.mux.HandleFunc("POST /api/flow-runs/{id}/nodes/{nodeId}/resolve", s.resolveFlowNode)
	s.mux.HandleFunc("POST /api/flow-runs/{id}/nodes/{nodeId}/merge/resolve", s.resolveFlowSandboxMerge)
	s.mux.HandleFunc("POST /api/executions/sandbox", s.startSandboxedExecution)
	s.mux.HandleFunc("POST /api/executions/{id}/launch", s.launchPendingExecution)
	s.mux.HandleFunc("POST /api/executions/{id}/cursor/start", s.beginCursorExecution)
	s.mux.HandleFunc("POST /api/executions/{id}/cursor/complete", s.completeCursorExecution)
	s.mux.HandleFunc("POST /api/executions/{id}/change-set", s.buildChangeSet)
	s.mux.HandleFunc("POST /api/executions/{id}/revert", s.revertExecution)
	s.mux.HandleFunc("GET /api/quests/{id}/outcome", s.questOutcome)
	s.mux.HandleFunc("GET /api/quests/{id}/evidence-bundle", s.questEvidenceBundle)
	s.mux.HandleFunc("GET /api/quests/{id}/replans", s.listQuestReplans)
	s.mux.HandleFunc("POST /api/quests/{id}/replan", s.replanQuest)
	s.mux.HandleFunc("POST /api/quests/{id}/revise-brief", s.reviseQuestBrief)
	s.mux.HandleFunc("POST /api/quests/{id}/revert", s.revertQuest)
	s.mux.HandleFunc("POST /api/flow-runs/{id}/nodes/{nodeId}/revert", s.revertFlowNode)
	s.mux.HandleFunc("POST /api/memories", s.saveMemory)
	s.mux.HandleFunc("DELETE /api/memories/{id}", s.deleteMemory)
	s.mux.HandleFunc("POST /api/usage", s.recordUsage)
	s.mux.HandleFunc("POST /api/budget", s.saveBudget)
	s.mux.HandleFunc("POST /api/budget/pricing", s.saveModelPricing)
	s.mux.HandleFunc("GET /api/statistics", s.statistics)
	s.mux.HandleFunc("POST /api/agent-improvements/{id}/rollback", s.rollbackAgentImprovement)
	s.mux.HandleFunc("POST /api/agent-improvements/{id}/promote", s.promoteAgentImprovement)
	s.mux.HandleFunc("POST /api/agent-improvements/{id}/reject", s.rejectAgentImprovement)
	s.mux.HandleFunc("GET /api/experience/search", s.searchExperience)
	s.mux.HandleFunc("POST /api/learning/manual/preview", s.previewManualLearning)
	s.mux.HandleFunc("POST /api/learning/manual/apply", s.applyManualLearning)
	s.mux.HandleFunc("GET /api/benchmarks", s.listAgentBenchmarks)
	s.mux.HandleFunc("POST /api/benchmarks", s.saveAgentBenchmark)
	s.mux.HandleFunc("POST /api/benchmarks/{id}/evaluate", s.evaluateAgentBenchmark)
	s.mux.HandleFunc("GET /api/benchmark-evaluations", s.listAgentBenchmarkEvaluations)
	s.mux.HandleFunc("POST /api/benchmark-comparisons", s.compareAgentBenchmarks)
	s.mux.HandleFunc("GET /api/docker", s.dockerOverview)
	s.mux.HandleFunc("GET /api/docker/logs", s.dockerLogs)
	s.mux.HandleFunc("POST /api/docker/containers/action", s.dockerContainerAction)
	s.mux.HandleFunc("POST /api/servers", s.saveServerProfile)
	s.mux.HandleFunc("GET /api/servers", s.listServerProfiles)
	s.mux.HandleFunc("DELETE /api/servers/{id}", s.deleteServerProfile)
	s.mux.HandleFunc("POST /api/servers/{id}/probe", s.probeServerProfile)
	s.mux.HandleFunc("POST /api/servers/{id}/list", s.listServerRemote)
	s.mux.HandleFunc("POST /api/servers/{id}/read", s.readServerRemote)
	s.mux.HandleFunc("GET /api/servers/{id}/terminal", s.serverTerminal)
	s.registerDBRoutes()
	s.registerMCPRoutes()
	s.registerConnectionRoutes()
	s.mux.HandleFunc("GET /api/events", s.events)
}
