// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function CancelRun(arg1) {
  return window['go']['app']['App']['CancelRun'](arg1);
}

export function CancelWorkflowRun(arg1) {
  return window['go']['app']['App']['CancelWorkflowRun'](arg1);
}

export function DeleteCustomTool(arg1) {
  return window['go']['app']['App']['DeleteCustomTool'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['app']['App']['DeleteWorkflow'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['app']['App']['OpenWorkspace'](arg1);
}

export function PreviewAgentRun(arg1) {
  return window['go']['app']['App']['PreviewAgentRun'](arg1);
}

export function PreviewContext(arg1) {
  return window['go']['app']['App']['PreviewContext'](arg1);
}

export function PreviewCustomTool(arg1) {
  return window['go']['app']['App']['PreviewCustomTool'](arg1);
}

export function ProbeProvider(arg1) {
  return window['go']['app']['App']['ProbeProvider'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function RebuildProjectIndex() {
  return window['go']['app']['App']['RebuildProjectIndex']();
}

export function ResolveApproval(arg1, arg2) {
  return window['go']['app']['App']['ResolveApproval'](arg1, arg2);
}

export function RevertPatch(arg1) {
  return window['go']['app']['App']['RevertPatch'](arg1);
}

export function RunDetails(arg1) {
  return window['go']['app']['App']['RunDetails'](arg1);
}

export function RunTerminalCommand(arg1) {
  return window['go']['app']['App']['RunTerminalCommand'](arg1);
}

export function Runs() {
  return window['go']['app']['App']['Runs']();
}

export function SaveCustomTool(arg1) {
  return window['go']['app']['App']['SaveCustomTool'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2);
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SaveWorkflow(arg1) {
  return window['go']['app']['App']['SaveWorkflow'](arg1);
}

export function SearchText(arg1) {
  return window['go']['app']['App']['SearchText'](arg1);
}

export function SelectWorkspace() {
  return window['go']['app']['App']['SelectWorkspace']();
}

export function SetWorkspaceBoundary(arg1) {
  return window['go']['app']['App']['SetWorkspaceBoundary'](arg1);
}

export function StartRun(arg1) {
  return window['go']['app']['App']['StartRun'](arg1);
}

export function StartWorkflow(arg1) {
  return window['go']['app']['App']['StartWorkflow'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function WorkflowRunDetails(arg1) {
  return window['go']['app']['App']['WorkflowRunDetails'](arg1);
}

export function WorkflowRuns() {
  return window['go']['app']['App']['WorkflowRuns']();
}

export function WorkspaceTree() {
  return window['go']['app']['App']['WorkspaceTree']();
}
