// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {domain} from '../models';
import {tools} from '../models';
import {workspace} from '../models';
import {context} from '../models';

export function Bootstrap():Promise<app.Bootstrap>;

export function CancelRun(arg1:string):Promise<void>;

export function CancelWorkflowRun(arg1:string):Promise<void>;

export function DeleteCustomTool(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<app.WorkspaceView>;

export function PreviewAgentRun(arg1:app.AgentRunPreviewRequest):Promise<app.AgentRunPreview>;

export function PreviewContext(arg1:Array<domain.RunContextInput>):Promise<domain.ContextPreview>;

export function PreviewCustomTool(arg1:app.CustomToolPreviewRequest):Promise<tools.CustomProcessPreview>;

export function ProbeProvider(arg1:app.ProviderProbeRequest):Promise<app.ProviderProbeResult>;

export function ReadFile(arg1:string):Promise<workspace.FileContent>;

export function RebuildProjectIndex():Promise<workspace.IndexStatus>;

export function ResolveApproval(arg1:string,arg2:boolean):Promise<void>;

export function RevertPatch(arg1:string):Promise<domain.PatchProposal>;

export function RunDetails(arg1:string):Promise<app.RunDetails>;

export function RunTerminalCommand(arg1:app.TerminalCommandRequest):Promise<app.TerminalCommandResult>;

export function Runs():Promise<Array<domain.Run>>;

export function SaveCustomTool(arg1:domain.CustomTool):Promise<domain.CustomTool>;

export function SaveFile(arg1:string,arg2:string):Promise<workspace.FileContent>;

export function SaveProfile(arg1:domain.AgentProfile):Promise<domain.AgentProfile>;

export function SaveWorkflow(arg1:domain.AgentWorkflow):Promise<domain.AgentWorkflow>;

export function SearchText(arg1:string):Promise<Array<workspace.Match>>;

export function SelectWorkspace():Promise<app.WorkspaceView>;

export function SetWorkspaceBoundary(arg1:string):Promise<void>;

export function StartRun(arg1:app.StartRunRequest):Promise<domain.Run>;

export function StartWorkflow(arg1:app.StartWorkflowRequest):Promise<domain.WorkflowRun>;

export function Startup(arg1:context.Context):Promise<void>;

export function WorkflowRunDetails(arg1:string):Promise<domain.WorkflowRun>;

export function WorkflowRuns():Promise<Array<domain.WorkflowRun>>;

export function WorkspaceTree():Promise<Array<domain.FileNode>>;
