// Browser bundle for the Agent Hub webview.
//
// `ui/client` is the editable source tree; `media/main.js` is the only file
// shipped in the VSIX. Keeping that boundary explicit lets screens move into
// modules without changing the CSP or the extension/webview protocol.
import { build } from 'esbuild'
import { statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const entry = join(here, 'client', 'main.js')
const outfile = join(here, '..', 'media', 'main.js')

await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  platform: 'browser',
  format: 'iife',
  target: ['es2022'],
  charset: 'utf8',
  legalComments: 'none',
  sourcemap: false,
  minify: false,
  logLevel: 'silent',
  banner: { js: '// Generated by ui/build-js.mjs. Edit ui/client/*, not this file.' },
})

console.log(JSON.stringify({ hubBundle: 'built', bytes: statSync(outfile).size }))
